# MODEL PARAMS
EPOCHS : 50
RESUME_CHECKPOINT : 
SAVE_EVERY_ITER : 20
VAL_EVERY_EPOCH : 1
BATCH_PLOT_EVERY_ITER : 20
OUTPUT_DIR : outputs
EXP_NAME : imgnet_T1

# DATA PARMS
TRAIN_FILENAME : iids_train.txt
TEST_FILENAME  : iids_test.txt
ROOT_DIR       : dataset/BSDS300/images

IMG_SIZE       : 64 
INP_CHANNELS   : 1
OUT_CHANNELS   : 1

# HYPER PARAMS
LR             : 0.001
WEIGHT_DECAY   : 0.
MOMENTUM       : 0.9
OPT            : Adam
SCHEDL         : lambdaLR
TRAIN_BATCH    : 1000
TEST_BATCH     : 1000
ALPHA1         : 0.001
ALPHA2         : 0.01
MASK_DEN       : 0.1
BIN_METH       : QUANT

#solver params
OFFSET         :
TAU            :
ITERATIONS     :
NOTE           : X (not imagenet normalized) being used for both MaskM and Solver
                 