# MODEL PARAMS
EPOCHS : 100
MODEL_TYPE : unet_standard
RESUME_CHECKPOINT : 
SAVE_EVERY_ITER : 50
VAL_EVERY_ITER : 25
BATCH_PLOT_EVERY_ITER : 25
OUTPUT_DIR : outputs
EXP_NAME : 14_4_JM_2

# DATA PARMS
TRAIN_FILENAME : iids_train.txt
TEST_FILENAME  : iids_test.txt
ROOT_DIR       : dataset/imagenet/images

IMG_SIZE       : 128
INP_CHANNELS   : 1
OUT_CHANNELS   : 1

# HYPER PARAMS unet
OPT            : 
    opt        : SGD-Nestrov
    lr         : 0.001
    wd         : 0.001
    momentum   : 0.009  

SCHEDL         : 
TRAIN_BATCH    : 2
TEST_BATCH     : 2
ALPHA1         : 1
ALPHA2         : 1
MASK_DEN       : 0.2
BIN_METH       : QUANT
MAX_NORM       : 1
SKIP_NORM      : 500

#solver params
SOLVER_TYPE    : Stab_BiCGSTAB
R_ABS_EPS      : 1e-3
OFFSET         : 0.004
TAU            : 8000
ITERATIONS     : 
OFFSET_EVL     : constant
OFFSET_EVL_STEPS : 5000
NOTE           : 


# Joint model params
MN_INP_CHANNELS : 1
MN_OUT_CHANNELS : 1

IN_INP_CHANNELS : 2
IN_OUT_CHANNELS : 1

RESUME_CHECKPOINT_MN : 
RESUME_CHECKPOINT_IN : 

OPT1 :
    opt : SGD-Nestrov
    lr : 0.001
    wd : 0.001
    momentum : 0.009
SCHEDL1 : 

OPT2 :
    opt : SGD-Nestrov
    lr : 0.001
    wd : 0.001
    momentum : 0.009
SCHEDL2 : 

RES_LOSS_OFFSET : 0.004

