# MODEL PARAMS
EPOCHS : 2
RESUME_CHECKPOINT : 
SAVE_EVERY_ITER : 10
VAL_EVERY_EPOCH : 10
BATCH_PLOT_EVERY_ITER : 10
OUTPUT_DIR : outputs
EXP_NAME : BSDS300_t6

# DATA PARMS
TRAIN_FILENAME : iids_train.txt
TEST_FILENAME  : iids_test.txt
ROOT_DIR       : dataset/BSDS300/images

IMG_SIZE       : 128 
INP_CHANNELS   : 1
OUT_CHANNELS   : 1

# HYPER PARAMS
LR             : 0.001
WEIGHT_DECAY   : 0.
MOMENTUM       : 0.9
OPT            : Adam
SCHEDL         : lambdaLR
TRAIN_BATCH    : 64
TEST_BATCH     : 64
ALPHA1         : 0.001
ALPHA2         : 0.1
MASK_DEN       : 0.1
BIN_METH       : QUANT

#solver params
OFFSET         :
TAU            :
ITERATIONS     :
NOTE           : X (not imagenet normalized) being used for both MaskM and Solver
                 