# MODEL PARAMS
EPOCHS : 10
RESUME_CHECKPOINT : 
SAVE_EVERY_ITER : 1000
VAL_EVERY_ITER : 1000
BATCH_PLOT_EVERY_ITER : 100
OUTPUT_DIR : outputs
EXP_NAME : 1_11_run_20

# DATA PARMS
TRAIN_FILENAME : iids_train.txt
TEST_FILENAME  : iids_test.txt
ROOT_DIR       : dataset/imagenet/images

IMG_SIZE       : 128
INP_CHANNELS   : 1
OUT_CHANNELS   : 2

# HYPER PARAMS unet
OPT            : 
    opt        : SGD-Nestrov
    lr         : 0.001
    wd         : 0.001
    momentum   : 0.009  

SCHEDL         : 
TRAIN_BATCH    : 8
TEST_BATCH     : 8
ALPHA1         : 0.01
ALPHA2         : 1
MASK_DEN       : 0.1
BIN_METH       : QUANT
MAX_NORM       : 1
SKIP_NORM      : 500

#solver params
R_ABS_EPS      : 1e-4
OFFSET         : 12
TAU            : 14000
ITERATIONS     : 
NOTE           : 

# Joint model params
MN_INP_CHANNELS : 1
MN_OUT_CHANNELS : 1

IN_INP_CHANNELS : 2
IN_OUT_CHANNELS : 1

RESUME_CHECKPOINT_MN : 
RESUME_CHECKPOINT_IN : 

OPT1 :
    opt : Adam
    lr : 0.00001
    wd : 0.001
    momentum : 0.009
SCHEDL1 : 

OPT2 :
    opt : Adam
    lr : 0.00001
    wd : 0.001
    momentum : 0.009
SCHEDL2 : 

RES_LOSS_OFFSET : 1


# rsync -pthrvz -e "condor_ssh_to_job" 65265:outputs/* ssh_output/
# rsync -pthrvz -e "condor_ssh_to_job" 65272:outputs/* ssh_output/
# rsync -pthrvz -e "condor_ssh_to_job" 65273:outputs/* ssh_output/rep/
# rsync -pthrvz -e "condor_ssh_to_job" 65275:outputs/* ssh_output/
# rsync -pthrvz -e "condor_ssh_to_job" 65400:outputs/* ssh_output/
# rsync -pthrvz -e "condor_ssh_to_job" 65414:outputs/* ssh_output/
# rsync -pthrvz -e "condor_ssh_to_job" 65409:outputs/* ssh_output/

# low rabs exp 15
# rsync -pthrvz -e "condor_ssh_to_job" 65472:outputs/* ssh_output/

# 2 mask  16, 17, 18, 19, 20
# rsync -pthrvz -e "condor_ssh_to_job" 65494:outputs/* ssh_output/
# rsync -pthrvz -e "condor_ssh_to_job" 65495:outputs/* ssh_output/
# rsync -pthrvz -e "condor_ssh_to_job" 65496:outputs/* ssh_output/
# rsync -pthrvz -e "condor_ssh_to_job" 65499:outputs/* ssh_output/
# rsync -pthrvz -e "condor_ssh_to_job" 65504:outputs/* ssh_output/

# JM - Finished
# rsync -pthrvz -e "condor_ssh_to_job" 65457:outputs/* ssh_output_new/
# rsync -pthrvz -e "condor_ssh_to_job" 65458:outputs/* ssh_output_new/
