# MODEL PARAMS
EPOCHS : 10
RESUME_CHECKPOINT : 
SAVE_EVERY : 10
VAL_EVERY : 10
OUTPUT_DIR : unet-bsds300


# DATA PARMS
TRAIN_FILENAME : iids_train.txt
TEST_FILENAME  : iids_test.txt
ROOT_DIR       : dataset\BSDS300\images\

IMG_SIZE       : 64 
INP_CHANNELS   : 1
OUT_CHANNELS   : 1

# HYPER PARAMS
LR             : 0.001
WEIGHT_DECAY   : 0.9
MOMENTUM       : 0.9
OPT            : SGD
SCHEDL         : exp
TRAIN_BATCH    : 8
TEST_BATCH     : 8
ALPHA          : 0.01
MASK_DEN       : 0.1
BIN_METH       : QUANT

#solver params
OFFSET         :
TAU            :
ITERATIONS     :
