# MODEL PARAMS
EPOCHS : 5
RESUME_CHECKPOINT : 
SAVE_EVERY_ITER : 1000
VAL_EVERY_ITER : 1000
BATCH_PLOT_EVERY_ITER : 100
OUTPUT_DIR : outputs
EXP_NAME : 29_10_run_1

# DATA PARMS
TRAIN_FILENAME : iids_train.txt
TEST_FILENAME  : iids_test.txt
ROOT_DIR       : dataset/BSDS300/images

IMG_SIZE       : 128
INP_CHANNELS   : 1
OUT_CHANNELS   : 1

# HYPER PARAMS unet
OPT            : 
    opt        : SGD-Nestrov
    lr         : 0.001
    wd         : 0.001
    momentum   : 0.009  

SCHEDL         : 
TRAIN_BATCH    : 8
TEST_BATCH     : 8
ALPHA1         : 0.01
ALPHA2         : 1
MASK_DEN       : 0.1
BIN_METH       : QUANT
MAX_NORM       : 1
SKIP_NORM      : 50

#solver params
R_ABS_EPS      : 1e-4
OFFSET         : 12
TAU            : 14000
ITERATIONS     : 
NOTE           : 

# Joint model params
MN_INP_CHANNELS : 1
MN_OUT_CHANNELS : 1

IN_INP_CHANNELS : 2
IN_OUT_CHANNELS : 1

RESUME_CHECKPOINT_MN : 
RESUME_CHECKPOINT_IN : 

OPT1 :
    opt : Adam
    lr : 0.00001
    wd : 0.001
    momentum : 0.009
SCHEDL1 : 

OPT2 :
    opt : Adam
    lr : 0.00001
    wd : 0.001
    momentum : 0.009
SCHEDL2 : 

RES_LOSS_OFFSET : 1
