# MODEL PARAMS
EPOCHS : 30
RESUME_CHECKPOINT : 
SAVE_EVERY_ITER : 100
VAL_EVERY_ITER : 20
BATCH_PLOT_EVERY_ITER : 20
OUTPUT_DIR : outputs
EXP_NAME : imagenet_T2

# DATA PARMS
TRAIN_FILENAME : iids_train.txt
TEST_FILENAME  : iids_test.txt
ROOT_DIR       : dataset/BSDS300/images

IMG_SIZE       : 64 
INP_CHANNELS   : 1
OUT_CHANNELS   : 1

# HYPER PARAMS
LR             : 0.001
WEIGHT_DECAY   : 0.01
MOMENTUM       : 0.9
OPT            : Adam
SCHEDL         : exp
TRAIN_BATCH    : 128
TEST_BATCH     : 128
ALPHA1         : 0.001
ALPHA2         : 0.01
MASK_DEN       : 0.1
BIN_METH       : QUANT

#solver params
OFFSET         :
TAU            :
ITERATIONS     :
NOTE           : warmup 5 epochs from 1e-5 and no lr scheduler after warmup; model levels inc 2 -> 3
                 