# MODEL PARAMS
EPOCHS : 50
RESUME_CHECKPOINT : 
SAVE_EVERY_ITER : 1000
VAL_EVERY_ITER : 13000
BATCH_PLOT_EVERY_ITER : 10
OUTPUT_DIR : outputs
EXP_NAME : temp_2

# DATA PARMS
TRAIN_FILENAME : iids_train.txt
TEST_FILENAME  : iids_test.txt
ROOT_DIR       : dataset/BSDS300/images

IMG_SIZE       : 128 
INP_CHANNELS   : 1
OUT_CHANNELS   : 1

# HYPER PARAMS unet

OPT            : 
    opt        : Adam
    lr         : 0.0001
    wd         : 0.001
    momentum   : 0.009  

SCHEDL         : 
TRAIN_BATCH    : 8
TEST_BATCH     : 8
ALPHA1         : 0.01
ALPHA2         : 1
MASK_DEN       : 0.1
BIN_METH       : QUANT
MAX_NORM       : 1
SKIP_NORM      : 50

# Joint model params
OPT1 :
    opt :
    lr : 
    wd : 
    momentum : 
SCHEDL1 : 

OPT2 :
    opt : 
    lr : 
    wd : 
    momentum : 
SCHEDL2 : 

#solver params
OFFSET         : 10
TAU            : 4096
ITERATIONS     : 
NOTE           : 

