# MODEL PARAMS
EPOCHS : 1
RESUME_CHECKPOINT : 
SAVE_EVERY : 10
VAL_EVERY : 10
OUTPUT_DIR : unet-bsds300


# DATA PARMS
TRAIN_FILENAME : iids_train.txt
TEST_FILENAME  : iids_test.txt
ROOT_DIR       : dataset/BSDS300-images/BSDS300/images/

IMG_SIZE       : 50 
INP_CHANNELS   : 1
OUT_CHANNELS   : 1

# HYPER PARAMS
LR             : 0.001
WEIGHT_DECAY   : 0.009
OPT            : Adam
SCHEDL         : exp
TRAIN_BATCH    : 2
TEST_BATCH     : 2



