# MODEL PARAMS
EPOCHS : 10
RESUME_CHECKPOINT : 
SAVE_EVERY_ITER : 100
VAL_EVERY_ITER : 1000
BATCH_PLOT_EVERY_ITER : 100
OUTPUT_DIR : outputs
EXP_NAME : 22_11_r1

# DATA PARMS
TRAIN_FILENAME : iids_train.txt
TEST_FILENAME  : iids_test.txt
ROOT_DIR       : dataset/imagenet/images

IMG_SIZE       : 128
INP_CHANNELS   : 1
OUT_CHANNELS   : 1

# HYPER PARAMS unet
OPT            : 
    opt        : Adam
    lr         : 0.00001
    wd         : 0.001
    momentum   : 0.009  

SCHEDL         : multiStep
TRAIN_BATCH    : 4
TEST_BATCH     : 4
ALPHA1         : 0.01
ALPHA2         : 1
MASK_DEN       : 0.1
BIN_METH       : QUANT
MAX_NORM       : 1
SKIP_NORM      : 500

#solver params
R_ABS_EPS      : 1e-3
OFFSET         : 0.09
TAU            : 14000
ITERATIONS     : 
NOTE           : 
OFFSET_EVL     : constant

# Joint model params
MN_INP_CHANNELS : 1
MN_OUT_CHANNELS : 1

IN_INP_CHANNELS : 2
IN_OUT_CHANNELS : 1

RESUME_CHECKPOINT_MN : 
RESUME_CHECKPOINT_IN : 

OPT1 :
    opt : Adam
    lr : 0.00001
    wd : 0.001
    momentum : 0.009
SCHEDL1 : 

OPT2 :
    opt : Adam
    lr : 0.00001
    wd : 0.001
    momentum : 0.009
SCHEDL2 : 

RES_LOSS_OFFSET : 1

# rsync -pthrvz -e "condor_ssh_to_job" 67835:outputs/* ssh_output/
# rsync -pthrvz -e "condor_ssh_to_job" 67855:outputs/* ssh_output/
# rsync -pthrvz -e "condor_ssh_to_job" 67857:outputs/* ssh_output/
# rsync -pthrvz -e "condor_ssh_to_job" 67911:outputs/* ssh_output/
# rsync -pthrvz -e "condor_ssh_to_job" 67913:outputs/* ssh_output/

