# MODEL PARAMS
EPOCHS : 4
RESUME_CHECKPOINT :
SAVE_EVERY_ITER : 1000
VAL_EVERY_ITER : 13000
BATCH_PLOT_EVERY_ITER : 50
OUTPUT_DIR : outputs
EXP_NAME : 23_10_run_6

# DATA PARMS
TRAIN_FILENAME : iids_train.txt
TEST_FILENAME  : iids_test.txt
ROOT_DIR       : dataset/imagenet/images

IMG_SIZE       : 64 
INP_CHANNELS   : 1
OUT_CHANNELS   : 1

# HYPER PARAMS unet
OPT            : 
    opt        : SGD-Nestrov
    lr         : 0.001
    wd         : 0.001
    momentum   : 0.009  
SCHEDL         : 
TRAIN_BATCH    : 1
TEST_BATCH     : 1
ALPHA1         : 0.01
ALPHA2         : 0.0001
MASK_DEN       : 0.1
BIN_METH       : QUANT
MAX_NORM       : 1
SKIP_NORM      : 100

# Joint model params
OPT1 :
    opt :
    lr : 
    wd : 
    momentum : 
SCHEDL1 : 

OPT2 :
    opt : 
    lr : 
    wd : 
    momentum : 
SCHEDL2 : 

#solver params
OFFSET         : 8
TAU            : 4096
ITERATIONS     : 
NOTE           : 

