# MODEL PARAMS
EPOCHS : 4
RESUME_CHECKPOINT : outputs/imagenet_t7/test_wts.pt
SAVE_EVERY_ITER : 1000
VAL_EVERY_ITER : 13000
BATCH_PLOT_EVERY_ITER : 50
OUTPUT_DIR : outputs
EXP_NAME : imagenet_t7

# DATA PARMS
TRAIN_FILENAME : iids_train.txt
TEST_FILENAME  : iids_test.txt
ROOT_DIR       : dataset/imagenet/images

IMG_SIZE       : 64 
INP_CHANNELS   : 1
OUT_CHANNELS   : 1

# HYPER PARAMS
LR             : 0.001
WEIGHT_DECAY   : 0.0001
MOMENTUM       : 0.009
OPT            : AdamW
SCHEDL         : multiStep
TRAIN_BATCH    : 8
TEST_BATCH     : 8
ALPHA1         : 0.01
ALPHA2         : 0.0001
MASK_DEN       : 0.1
BIN_METH       : QUANT
MAX_NORM       : 1
SKIP_NORM      : 50

#solver params
OFFSET         : 8
TAU            : 4096
ITERATIONS     : 
NOTE           : 

