# USED TO CREATE DIRECTORIES (REQUIRED)
PROJECT_NAME : Mainberger_NLPE
EXP_NAME : EXP_5

# IMAGE PATH
IMG_PTH : ../imgs/natural/scarf.pgm

# SOLVER PARAMS
EPS : 1e-3
SAVE_IMG_EVRY_ITER : 50

# PROBABALISTIC SPARSIFICATION PARAMS
P : 0.02
Q : 0.02
DEN : 0.3

# NLPE PARAMS
NLPE : True
ITER : 100
M : 10
N : 1

# BELCHAMI PARAMS